import os

print  "os.path.abspath(__file__)      : "+ os.path.abspath(__file__)
print  "os.path.basename(__file__)     : "+ os.path.basename(__file__)
print  "os.path.commonprefix(__file__) : "+ os.path.commonprefix(__file__)
print  "os.path.dirname(__file__)      : "+ os.path.dirname(__file__)
print  "os.path.exists(__file__)       : " + str( os.path.exists(__file__) )
print  "os.path.lexists(__file__)      : "+ str( os.path.lexists(__file__) )
print  "os.path.getatime(__file__)     : "+ str( os.path.getatime(__file__) )
print  "os.path.getmtime(__file__)     : "+ str( os.path.getmtime(__file__) )
print  "os.path.getctime(__file__)     : "+ str( os.path.getctime(__file__) )
print  "os.path.getsize(__file__)      : "+ str(  os.path.getsize(__file__) )
print  "os.path.normcase(__file__)     : "+ os.path.normcase(__file__)
print  "os.path.normcase(__file__)     : "+ os.path.normcase(__file__)
print  "os.path.isfile(__file__)       : "+ str(  os.path.isfile(__file__) )
print  "os.path.isdir(__file__)        : "+ str(  os.path.isdir(__file__) )
print  "os.path.islink(__file__)       : "+ str(  os.path.islink(__file__) )
print  "os.path.ismount(__file__)      : "+ str(  os.path.ismount(__file__) )
print  "os.path.normcase(__file__)     : "+ os.path.normcase(__file__)
print  "os.path.normpath(__file__)     : "+ os.path.normpath(__file__)
print  "os.path.realpath(__file__)     : "+ os.path.realpath(__file__)
print  "os.path.relpath(__file__)      : "+ os.path.relpath(__file__)
print  "os.path.relpath(__file__)      : "+ os.path.relpath(__file__)
print  "os.path.split(__file__)        : "+ str(  os.path.split(__file__) )
print  "os.path.splitdrive(__file__)   : "+ str(  os.path.splitdrive(__file__) )
print  "os.path.splitext(__file__)     : "+ str(  os.path.splitext(__file__) )
print  "os.path.splitunc(__file__)     : "+ str(  os.path.splitunc(__file__) )
print  "os.path.supports_unicode_filenames : " + str(  os.path.supports_unicode_filenames )
